# Generated by Django 5.2.2 on 2025-06-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_remove_cart_filter_replacement_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(choices=[('filtration_system', 'ReelzAir Purifier'), ('filter_replacement', 'ReelzAir Filter Replacement')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
