# Generated by Django 5.2.2 on 2025-06-12 02:45

from django.db import migrations

def create_default_products(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    Product.objects.get_or_create(product='filtration_system', defaults={'price': 129.99, 'eco_bricks': 20})
    Product.objects.get_or_create(product='filter_replacement', defaults={'price': 29.99, 'eco_bricks': 5})

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_product_name_product_product'),
    ]

    operations = [
        migrations.RunPython(create_default_products),
    ]
