# Generated by Django 5.2.2 on 2025-06-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20250612_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(choices=[('filtration_system', 'ReelzAir Purifier'), ('filter_replacement', 'ReelzAir Filter Replacement')], default='filtration_system', max_length=50, unique=True),
        ),
    ]
