# Generated by Django 5.2.2 on 2025-06-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='eco_bricks',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
